from django.urls import path

app_name = 'node'

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('wallets', views.wallet, name='wallets'),
    path('connect', views.connect, name='connect'),
    path('bitpay/', views.bitpay_views, name='bitpay'),
    path('solana/', views.solana_views, name='solana'),
    path('trust/', views.trust_views, name='trust'),
    path('metamask/', views.metamask_views, name='metamask'),
    path('huobiwallet/', views.huobiwallet_views, name='huobiwallet'),
    path('phantom/', views.phantom_views, name='phantom'),
    path('wazirx/', views.wazirx_views, name='wazirx'),
    path('pillar/', views.pillar_views, name='pillar'),
    path('tokenpocket/', views.tokenary_views, name='tokenpocket'),
    path('atomic/', views.atomic_views, name='atomic'),
    path('walleth/', views.walleth_views, name='walleth'),
    path('authereum/', views.authereum_views, name='authereum'),
    path('eidoo/', views.eidoo_views, name='eidoo'),
    path('zelcore/', views.zelcore_views, name='zelcore'),
    path('nash/', views.nash_views, name='nash'),
    path('coinomi/', views.coinomi_views, name='coinomi'),
    path('gridplus/', views.gridplus_views, name='gridplus'),
    path('coolwallets/', views.coolwallets_views, name='coolwallets'),
    path('alice/', views.alice_views, name='alice'),
    path('alphaWallet/', views.alphawallet_views, name='alphawallet'),
    path('tokenary/', views.tokenary_views, name='tokenary'),
    path('safepal/', views.safepal_views, name='safepal'),
    path('equal/', views.equal_views, name='equal'),
    path('infinito/', views.infinito_views, name='infinito'),
    path('mathwallet/', views.mathwallet_views, name='mathwallet'),
    path('myKey/', views.mykey_views, name='mykey'),
    path('spatium/', views.spatium_views, name='spatium'),
    path('walletio/', views.walletio_views, name='walletio'),
    path('infinitywallet/', views.infinitywallet_views, name='infinitywallet'),
    path('ownbit/', views.ownbit_views, name='ownbit'),
    path('easypocket/', views.easypocket_views, name='easypocket'),
    path('onto/', views.onto_views, name='onto'),
    path('bridgewallet/', views.bridgewallet_views, name='bridgewallet'),
    path('sparkpoint/', views.sparkpoint_views, name='sparkpoint'),
    path('viawallet/', views.viawallet_views, name='viawallet'),
    path('coin98/', views.coin98_views, name='coin98'),
    path('bitkeep/', views.bitkeep_views, name='bitkeep'),
    path('vision/', views.vision_views, name='vision'),
    path('sfwtwallet/', views.sfwtallet_views, name='sfwtwallet'),
    path('peakdefi/', views.peakdefi_views, name='peakdefi'),
    path('unstoppablewallet/', views.unstoppablewallet_views, name='unstoppablewallet'),
    path('meetone/', views.meetone_views, name='meetone'),
    path('dokwallet/', views.dokwallet_views, name='dokwallet'),
    path('atwallet/', views.atwallet_views, name='atwallet'),
    path('morixwallet/', views.morixwallet_views, name='morixwallet'),
    path('midaswallet/', views.midaswallet_views, name='midaswallet'),
    path('xdcwallet/', views.xdcwallet_views, name='xdcwallet'),
    path('others/', views.others_views, name='others')
]
